table Annual
	lineageTag: a4d731a1-b724-460f-9530-5a3134ac9b8c

	column year_number
		dataType: int64
		lineageTag: c59793b6-99ba-4c7b-84bc-67fbcda144c7
		summarizeBy: sum
		sourceColumn: year_number

	column months_covered
		dataType: int64
		lineageTag: dc21fada-cc47-47a2-b32c-7161b6b4efa5
		summarizeBy: sum
		sourceColumn: months_covered

	column transaction_lines
		dataType: int64
		lineageTag: edcea95a-7794-4518-b42a-84b0d8461612
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: 64fa07ad-2928-410a-aaec-dca8611405bc
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: 5aff0a4a-f71e-496e-ad79-33be4fec12c8
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 9750f791-5913-4265-80cd-24014be83e2c
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_month
		dataType: double
		lineageTag: 3aa2b3f2-7588-4b25-b933-143028fb54e9
		summarizeBy: sum
		sourceColumn: revenue_per_month

	column avg_line_value
		dataType: double
		lineageTag: 67511fb5-0339-46b2-acfb-3ad7f9c5a378
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: b710588f-f38b-4e76-90eb-8c381d0825ec
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Annual = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "annual.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_number", Int64.Type}, {"months_covered", Int64.Type}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_month", type number}, {"avg_line_value", type number}, {"margin_pct", type number}})
				in
				    Typed
