table Annual
	lineageTag: de20fd70-14ea-4c43-a129-3dc27c827588

	column year_number
		dataType: int64
		lineageTag: be0e18c5-ed3c-48d1-9869-df57483b23ee
		summarizeBy: sum
		sourceColumn: year_number

	column months_covered
		dataType: int64
		lineageTag: ee9823b5-440e-4eb5-bc17-8bba7d87a6a2
		summarizeBy: sum
		sourceColumn: months_covered

	column transaction_lines
		dataType: int64
		lineageTag: 397a8375-7435-471d-a090-85908bfc783c
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: 61df3441-0f55-4c5e-8696-dbc69e603cf7
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: fe5b017a-59b6-4dea-a4a1-c8d1378c9bb4
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 1ce22e92-ad36-4cd0-bfcc-8503429c3014
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_month
		dataType: double
		lineageTag: 669c5fde-1f8e-410c-9698-d8547ddd75df
		summarizeBy: sum
		sourceColumn: revenue_per_month

	column avg_line_value
		dataType: double
		lineageTag: 88539846-3bd8-4b56-bd8b-1730d997cc6f
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: f61fdcb9-8d2f-45ac-b13e-584b46d1441e
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Annual = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "annual.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_number", Int64.Type}, {"months_covered", Int64.Type}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_month", type number}, {"avg_line_value", type number}, {"margin_pct", type number}})
				in
				    Typed
