table Annual
	lineageTag: 69bfe25e-0342-48d8-a6e8-ab744917ff5e

	column year_number
		dataType: int64
		lineageTag: ff35657c-137f-47cd-8bfe-adc7727ad5b2
		summarizeBy: sum
		sourceColumn: year_number

	column months_covered
		dataType: int64
		lineageTag: c65402fb-ebd1-4fcd-a788-7a1ecdb5ac91
		summarizeBy: sum
		sourceColumn: months_covered

	column transaction_lines
		dataType: int64
		lineageTag: 2a9447db-c09e-4c18-833b-010b25a442ad
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: fc85904a-fa62-4fe6-bffd-0fccac47ebde
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: c466c180-25de-424f-9bb3-e2e6b63c8f8a
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: b6fa04ad-65c3-4c69-bd78-13b03fd92305
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_month
		dataType: double
		lineageTag: 71bb0ace-475f-4456-b462-830ee74ed106
		summarizeBy: sum
		sourceColumn: revenue_per_month

	column avg_line_value
		dataType: double
		lineageTag: 4b8d0452-9beb-4052-b26e-a65899e1c824
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: 25b862d2-bdc8-467e-b77b-f8ba12c3cda5
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Annual = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "annual.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_number", Int64.Type}, {"months_covered", Int64.Type}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_month", type number}, {"avg_line_value", type number}, {"margin_pct", type number}})
				in
				    Typed
