table Annual
	lineageTag: 5ab6f230-c4b6-468c-9d21-f8f2e7f92978

	column year_number
		dataType: int64
		lineageTag: 56dbe95d-6c67-46e8-8130-0ec4035d5d7f
		summarizeBy: sum
		sourceColumn: year_number

	column months_covered
		dataType: int64
		lineageTag: 1e67f489-521e-458e-a487-ad4e0febb994
		summarizeBy: sum
		sourceColumn: months_covered

	column transaction_lines
		dataType: int64
		lineageTag: c972a505-71cd-419a-9413-506ca1d602e0
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: a24c4bf3-8127-439a-83dd-a908de0c0ceb
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: 578ff2a4-ce40-4e92-a930-ac0647285cab
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 9a047e85-7b7d-4710-acca-cfd27c7938c9
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_month
		dataType: double
		lineageTag: b9cf8dd7-6b0e-4fce-b528-6cc3b350f636
		summarizeBy: sum
		sourceColumn: revenue_per_month

	column avg_line_value
		dataType: double
		lineageTag: 2cbc78a8-3add-4685-867c-29a2ee29773d
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: 76ccc96f-e242-4ec1-bdeb-1e38b6d0705d
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Annual = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "annual.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_number", Int64.Type}, {"months_covered", Int64.Type}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_month", type number}, {"avg_line_value", type number}, {"margin_pct", type number}})
				in
				    Typed
