table CategoryMonth
	lineageTag: 46177e32-018f-4bcc-9347-13d5c66cd735

	column year_month
		dataType: string
		lineageTag: 83dddcb1-e8fb-42b6-abb7-d0d40f6700b6
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: 3115fe1b-1b72-453c-a2a1-1c8f79906de6
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column year_number
		dataType: int64
		lineageTag: a4576b13-78f1-4654-83e3-43aebce962d2
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 6783e697-3986-444d-92b1-9d92ba8c1a49
		summarizeBy: sum
		sourceColumn: quarter_number

	column category_name
		dataType: string
		lineageTag: 633d60a9-1aca-48cf-b05b-4039df64bfb0
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: bc9fab6b-cf37-4571-8e65-28270a980fe5
		summarizeBy: none
		sourceColumn: sub_category_name

	column transaction_lines
		dataType: int64
		lineageTag: b18db111-3429-4a73-b0e4-fef2f5205344
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: 61218454-17e0-436d-88cf-8eb4395c44ed
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: f807a181-edfa-4ef0-a41b-21d948a15684
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: de5a6feb-b13d-41b5-9918-ea190449a9c1
		summarizeBy: sum
		sourceColumn: profit

	column margin_pct
		dataType: double
		lineageTag: 0e8ac39f-f80f-4cca-a714-4ee2f45384f9
		summarizeBy: sum
		sourceColumn: margin_pct

	partition CategoryMonth = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "category_month.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_month", type text}, {"month_start", type date}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"category_name", type text}, {"sub_category_name", type text}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"margin_pct", type number}})
				in
				    Typed
