table CategoryMonth
	lineageTag: 2231024c-8b96-4b8b-aa0b-46c192d42f34

	column year_month
		dataType: string
		lineageTag: b4b0d1a7-9f8e-4aff-9ad8-04b2ba23fcf6
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: 402b68b0-0d7d-4348-b691-83cf902a908c
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column year_number
		dataType: int64
		lineageTag: 28b0e2aa-07b6-4d4d-9acd-70d7f7cc62fc
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 8ff382d5-8e0f-40a4-8a3e-a325d7a68e05
		summarizeBy: sum
		sourceColumn: quarter_number

	column category_name
		dataType: string
		lineageTag: 83139e7c-0b48-40a4-a544-c084cb227bf9
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: 07d304e9-9e38-400f-b5ce-7136d6843f7a
		summarizeBy: none
		sourceColumn: sub_category_name

	column transaction_lines
		dataType: int64
		lineageTag: f16571a9-9dd7-489d-8e92-7c89e1c9b8a9
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: cbdde3af-f108-45f2-b8d4-9091331e45de
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: ae0e708a-df2c-4481-8dbd-9d60298a5327
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: b1ce56b6-31e7-467d-ab71-fc8b6c9d06ff
		summarizeBy: sum
		sourceColumn: profit

	column margin_pct
		dataType: double
		lineageTag: 0f9c227f-e5b6-49be-b708-2e7867996ae3
		summarizeBy: sum
		sourceColumn: margin_pct

	partition CategoryMonth = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "category_month.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_month", type text}, {"month_start", type date}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"category_name", type text}, {"sub_category_name", type text}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"margin_pct", type number}})
				in
				    Typed
