table CategoryMonth
	lineageTag: 3d80d795-c813-451e-9716-5f18f6bfc2d6

	column year_month
		dataType: string
		lineageTag: 100fa2d9-8aa2-448a-81ab-3bd9f565ea12
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: e452cd8b-50fd-42d5-9e9f-357c0c7839a2
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column year_number
		dataType: int64
		lineageTag: 2f763e11-34ab-41f9-bdb0-d249b8c412f2
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 315b7c3f-7d1a-4d23-8da0-a0d05276bcd5
		summarizeBy: sum
		sourceColumn: quarter_number

	column category_name
		dataType: string
		lineageTag: 1b429a40-188d-4ded-86b8-6489fb8202b2
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: 0c55c328-9d81-4296-800b-320b76cb5d64
		summarizeBy: none
		sourceColumn: sub_category_name

	column transaction_lines
		dataType: int64
		lineageTag: 30c95347-d357-4dee-899d-43f8ed6ed0ce
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: 08b5b692-350a-4013-b254-5408ee12a658
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: edb47040-0b30-4d6b-bd98-3f2478bbdf18
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 8b39a9ac-0198-4983-ba02-14cdeedcd9f1
		summarizeBy: sum
		sourceColumn: profit

	column margin_pct
		dataType: double
		lineageTag: 5c30e893-ad33-41af-a247-3ed9cbd666c7
		summarizeBy: sum
		sourceColumn: margin_pct

	partition CategoryMonth = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "category_month.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_month", type text}, {"month_start", type date}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"category_name", type text}, {"sub_category_name", type text}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"margin_pct", type number}})
				in
				    Typed
