table CustomerSegments
	lineageTag: a5f604b8-a51f-45f8-a0ad-02bb70d3109d

	column customer_id
		dataType: int64
		lineageTag: e29f07f9-b362-4ee4-a884-cfd9dd09444c
		summarizeBy: sum
		sourceColumn: customer_id

	column customer_name
		dataType: string
		lineageTag: 3481d689-1a6b-4738-98a8-59d2b11c0269
		summarizeBy: none
		sourceColumn: customer_name

	column city_name
		dataType: string
		lineageTag: 3e983daa-eb88-4888-859f-3fd2523fed10
		summarizeBy: none
		sourceColumn: city_name

	column state_name
		dataType: string
		lineageTag: c64c2432-8a86-4cf4-a979-40d1cb531aa8
		summarizeBy: none
		sourceColumn: state_name

	column transaction_lines
		dataType: int64
		lineageTag: 15691cda-783a-40fd-9349-d20a39688047
		summarizeBy: sum
		sourceColumn: transaction_lines

	column revenue
		dataType: double
		lineageTag: e2428857-2b48-44ef-b91b-48ec4e71e91d
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 53fbebd0-4374-4ef1-a201-9003d2fb1352
		summarizeBy: sum
		sourceColumn: profit

	column margin_pct
		dataType: double
		lineageTag: 2e1f7a3b-cc10-4679-a839-da7bd300085b
		summarizeBy: sum
		sourceColumn: margin_pct

	column recency_days
		dataType: int64
		lineageTag: 07c3750f-b78d-41ad-9604-1b259bc5ab24
		summarizeBy: sum
		sourceColumn: recency_days

	column cluster
		dataType: int64
		lineageTag: d1af73fa-c6b9-49d3-af76-a967867f93ee
		summarizeBy: sum
		sourceColumn: cluster

	column segment
		dataType: string
		lineageTag: ee41efd4-9847-44fb-81b5-59a58c10e388
		summarizeBy: none
		sourceColumn: segment

	measure 'Segment Customers' = COUNTROWS ( CustomerSegments )
		formatString: #,0
		lineageTag: a2b3c7f8-1d12-4d44-89be-0c9c29df303e

	measure 'Segment Revenue' = SUM ( CustomerSegments[revenue] )
		formatString: #,0
		lineageTag: c26a40fc-2a73-461d-84b8-3db36f818958

	measure 'Segment Profit' = SUM ( CustomerSegments[profit] )
		formatString: #,0
		lineageTag: 3108dce4-5faa-4d3e-8dd8-89e99bf00ac6

	measure 'Segment Margin %' = DIVIDE ( [Segment Profit], [Segment Revenue] ) * 100
		formatString: #,0.00
		lineageTag: 2b828bbd-d635-4056-bd8a-51ae5d4fd35b

	measure 'Segment % of Customers' = DIVIDE ( [Segment Customers], CALCULATE ( [Segment Customers], ALL ( CustomerSegments ) ) ) * 100
		formatString: #,0.0
		lineageTag: 67512f8b-73f9-4c0f-a6d5-7eb0e034f352

	measure 'Segment % of Revenue' = DIVIDE ( [Segment Revenue], CALCULATE ( [Segment Revenue], ALL ( CustomerSegments ) ) ) * 100
		formatString: #,0.0
		lineageTag: cd1249b3-7305-4e22-a73a-6294304b203d

	measure 'Segment % of Profit' = DIVIDE ( [Segment Profit], CALCULATE ( [Segment Profit], ALL ( CustomerSegments ) ) ) * 100
		formatString: #,0.0
		lineageTag: 12721d31-58db-41ea-aad7-3b783811fc50

	partition CustomerSegments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "customer_segments.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", Int64.Type}, {"customer_name", type text}, {"city_name", type text}, {"state_name", type text}, {"transaction_lines", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"margin_pct", type number}, {"recency_days", Int64.Type}, {"cluster", Int64.Type}, {"segment", type text}})
				in
				    Typed
