table CustomerSegments
	lineageTag: ed53ea2a-ac1b-4267-ab26-0e3921bb87fe

	column customer_id
		dataType: int64
		lineageTag: 4423d4ed-fe7b-48c2-b86c-c589b6ebac5e
		summarizeBy: sum
		sourceColumn: customer_id

	column customer_name
		dataType: string
		lineageTag: b56db948-2588-4ba5-bad3-142a1aef6970
		summarizeBy: none
		sourceColumn: customer_name

	column city_name
		dataType: string
		lineageTag: d91e335e-0936-404d-bed3-7474b073fe5c
		summarizeBy: none
		sourceColumn: city_name

	column state_name
		dataType: string
		lineageTag: f891aac8-6fef-43b4-863d-32c05827d98c
		summarizeBy: none
		sourceColumn: state_name

	column transaction_lines
		dataType: int64
		lineageTag: c7091b41-985e-44ed-aa57-27ce8f965ff8
		summarizeBy: sum
		sourceColumn: transaction_lines

	column revenue
		dataType: double
		lineageTag: 46f5c1e0-88f1-4cd1-a65c-4d3399d5d6fd
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 0729b0dd-cc5e-489e-b1c8-856f36daac3b
		summarizeBy: sum
		sourceColumn: profit

	column margin_pct
		dataType: double
		lineageTag: ed32c867-f94f-4117-a83a-9aad3515c8a2
		summarizeBy: sum
		sourceColumn: margin_pct

	column recency_days
		dataType: int64
		lineageTag: 8f39ff14-a8fe-4bac-8af5-26da30d9bae3
		summarizeBy: sum
		sourceColumn: recency_days

	column cluster
		dataType: int64
		lineageTag: cb34bfdd-9675-49d6-9591-c98ff18241da
		summarizeBy: sum
		sourceColumn: cluster

	column segment
		dataType: string
		lineageTag: 7d9dfa66-ace2-41f2-a841-f21b40c6a80e
		summarizeBy: none
		sourceColumn: segment

	measure 'Segment Customers' = COUNTROWS ( CustomerSegments )
		formatString: #,0
		lineageTag: 5186f241-5ef8-414d-b321-12f7298c15fb

	measure 'Segment Revenue' = SUM ( CustomerSegments[revenue] )
		formatString: #,0
		lineageTag: a618cc9f-8f96-4b18-a27b-e369546ef175

	measure 'Segment Profit' = SUM ( CustomerSegments[profit] )
		formatString: #,0
		lineageTag: e403782b-59a5-4ede-9e68-5cc5012e3422

	measure 'Segment Margin %' = DIVIDE ( [Segment Profit], [Segment Revenue] ) * 100
		formatString: #,0.00
		lineageTag: 32296943-c07c-4d07-b4c1-038b9a1d6b6a

	measure 'Segment % of Customers' = DIVIDE ( [Segment Customers], CALCULATE ( [Segment Customers], ALL ( CustomerSegments ) ) ) * 100
		formatString: #,0.0
		lineageTag: f3b8436b-d062-4a56-9921-182dddaf34ca

	measure 'Segment % of Revenue' = DIVIDE ( [Segment Revenue], CALCULATE ( [Segment Revenue], ALL ( CustomerSegments ) ) ) * 100
		formatString: #,0.0
		lineageTag: 714255ec-f9e0-4284-949c-e71baf4b4525

	measure 'Segment % of Profit' = DIVIDE ( [Segment Profit], CALCULATE ( [Segment Profit], ALL ( CustomerSegments ) ) ) * 100
		formatString: #,0.0
		lineageTag: 7428f44a-8a7a-479f-97df-5ce9ea5768cb

	partition CustomerSegments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "customer_segments.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", Int64.Type}, {"customer_name", type text}, {"city_name", type text}, {"state_name", type text}, {"transaction_lines", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"margin_pct", type number}, {"recency_days", Int64.Type}, {"cluster", Int64.Type}, {"segment", type text}})
				in
				    Typed
