table Geography
	lineageTag: f4ed4a11-dbae-4820-967a-126524459f3d

	column state_name
		dataType: string
		lineageTag: bfd23010-ad73-4e52-a0d4-64876df3532a
		summarizeBy: none
		sourceColumn: state_name

	column city_name
		dataType: string
		lineageTag: 8e026195-4d70-4b8f-93ec-87f95104e92f
		summarizeBy: none
		sourceColumn: city_name

	column transaction_lines
		dataType: int64
		lineageTag: a2423c37-4ea7-4371-a505-d0f2f86b1413
		summarizeBy: sum
		sourceColumn: transaction_lines

	column customers
		dataType: int64
		lineageTag: 82a97571-407f-40e0-972c-35c3f5766274
		summarizeBy: sum
		sourceColumn: customers

	column revenue
		dataType: double
		lineageTag: 0622b92b-65b0-4035-b333-d7585ced79cf
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 25e7ebac-6724-4246-8948-e62586f8e9e9
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_customer
		dataType: double
		lineageTag: e1ebd227-9582-4625-b39d-caff8ce6b023
		summarizeBy: sum
		sourceColumn: revenue_per_customer

	column margin_pct
		dataType: double
		lineageTag: 50b87715-3949-48bd-b213-346d01a74ebe
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "geography.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"state_name", type text}, {"city_name", type text}, {"transaction_lines", Int64.Type}, {"customers", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_customer", type number}, {"margin_pct", type number}})
				in
				    Typed
