table Geography
	lineageTag: 91e2ff21-2a63-4bc0-b042-a8c1d25dae89

	column state_name
		dataType: string
		lineageTag: e4b96e1d-bdad-4ec3-bb00-3bb80f7cf6b4
		summarizeBy: none
		sourceColumn: state_name

	column city_name
		dataType: string
		lineageTag: 2c655a61-2c72-4561-9016-f8439924ecb0
		summarizeBy: none
		sourceColumn: city_name

	column transaction_lines
		dataType: int64
		lineageTag: 06bb3425-780b-4298-8f09-50efb4abb956
		summarizeBy: sum
		sourceColumn: transaction_lines

	column customers
		dataType: int64
		lineageTag: f293133f-b515-4799-b950-6d2116f852c9
		summarizeBy: sum
		sourceColumn: customers

	column revenue
		dataType: double
		lineageTag: 70b0326c-e43a-458f-9680-ca8662a0e581
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 951dca7a-6da9-42b0-8ac5-8964669ce8e3
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_customer
		dataType: double
		lineageTag: fa28097a-1bd9-42cb-99bf-0db5397d459a
		summarizeBy: sum
		sourceColumn: revenue_per_customer

	column margin_pct
		dataType: double
		lineageTag: 10c6710e-e75b-431f-9d03-108f42a94e87
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "geography.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"state_name", type text}, {"city_name", type text}, {"transaction_lines", Int64.Type}, {"customers", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_customer", type number}, {"margin_pct", type number}})
				in
				    Typed
