table Geography
	lineageTag: a17b0b47-24d7-4765-b3df-72e6d3cba709

	column state_name
		dataType: string
		lineageTag: d3ee9287-a6c7-40da-983e-0cb7b04e7e00
		summarizeBy: none
		sourceColumn: state_name

	column city_name
		dataType: string
		lineageTag: 9fab40c4-c27d-46e8-9a65-07b335b52adc
		summarizeBy: none
		sourceColumn: city_name

	column transaction_lines
		dataType: int64
		lineageTag: 26ec927e-15f6-4c54-90cb-9a46de54feed
		summarizeBy: sum
		sourceColumn: transaction_lines

	column customers
		dataType: int64
		lineageTag: 62cd0ace-0a08-404d-b6e2-f939188c8349
		summarizeBy: sum
		sourceColumn: customers

	column revenue
		dataType: double
		lineageTag: 8c3a562d-07b1-49e5-b606-f02036c4e22b
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 1d998cdc-f05b-4ca3-a20e-5bb077a9e48e
		summarizeBy: sum
		sourceColumn: profit

	column revenue_per_customer
		dataType: double
		lineageTag: 83749302-c752-473b-8cb8-1d8b4124f012
		summarizeBy: sum
		sourceColumn: revenue_per_customer

	column margin_pct
		dataType: double
		lineageTag: f838009f-a8d3-43f5-b964-b9e4a7679f9d
		summarizeBy: sum
		sourceColumn: margin_pct

	partition Geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "geography.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"state_name", type text}, {"city_name", type text}, {"transaction_lines", Int64.Type}, {"customers", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"revenue_per_customer", type number}, {"margin_pct", type number}})
				in
				    Typed
