table Monthly
	lineageTag: 55276f59-1a07-4233-a83b-bfcf304bc506

	column year_month
		dataType: string
		lineageTag: 12d28542-c752-4ebf-b1e2-ad35676b71eb
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: 3c4d0155-8683-4cb9-852e-2833ac44d95c
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column year_number
		dataType: int64
		lineageTag: bbf77f73-9701-4f9f-9613-e58625bdc0ef
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: a2fe7ae6-44a4-4251-b90c-bee9ef366e2d
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: 06cb9102-da40-4f66-a6a6-6a1e13f7f5c9
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 0e5be2e1-66c5-4ba1-954d-78c05bae356d
		summarizeBy: none
		sourceColumn: month_name

	column transaction_lines
		dataType: int64
		lineageTag: c1f082eb-9dda-4aef-83aa-6f3e9c358b1c
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: ef8d16d1-d8a3-44f0-ae10-e30fd45341d3
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: 5df3fa18-0278-43b4-8038-7b05842a140a
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 931077bd-cfc1-4000-84f6-61523d409a82
		summarizeBy: sum
		sourceColumn: profit

	column avg_line_value
		dataType: double
		lineageTag: 916674c7-d1d1-4251-9052-53ac15b27a57
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: 627d328d-da2d-4344-8a4a-8d32351328b4
		summarizeBy: sum
		sourceColumn: margin_pct

	column in_analysis_window
		dataType: int64
		lineageTag: 853f8e6f-ece3-4662-9942-3c9108d153c3
		summarizeBy: sum
		sourceColumn: in_analysis_window

	partition Monthly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "monthly.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_month", type text}, {"month_start", type date}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"avg_line_value", type number}, {"margin_pct", type number}, {"in_analysis_window", Int64.Type}})
				in
				    Typed
