table Monthly
	lineageTag: 0e5ff028-c3fc-47cd-82ad-a474388f6510

	column year_month
		dataType: string
		lineageTag: 2e45d892-db73-4666-b9c8-a5e0c33b20c9
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: ed86e894-93f5-4772-a1dc-da3635891c2e
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column year_number
		dataType: int64
		lineageTag: 13d94501-1a91-47a3-a0b4-8ac25a206ce8
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 94d2c600-1f6a-44ba-880b-fce786e51862
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: 069734de-9ddc-40b6-bd55-101657996840
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 6566e021-7920-469f-836e-2386bda9a25f
		summarizeBy: none
		sourceColumn: month_name

	column transaction_lines
		dataType: int64
		lineageTag: 434f6cb8-31cd-4c48-907e-aeec3cc8551b
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: e7671e00-70ed-4cf4-96cb-bc3e43a57130
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: 14842411-c2bb-4317-bc9b-97f01969bf81
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 96219826-b2d6-419d-a890-2f140b1e83ea
		summarizeBy: sum
		sourceColumn: profit

	column avg_line_value
		dataType: double
		lineageTag: 5566f430-d5b8-455b-9c46-7706b09ca981
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: 41295d1e-f67b-4eba-90f7-3172958eeeee
		summarizeBy: sum
		sourceColumn: margin_pct

	column in_analysis_window
		dataType: int64
		lineageTag: 979b1946-1d7e-418a-b871-478364a76061
		summarizeBy: sum
		sourceColumn: in_analysis_window

	partition Monthly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "monthly.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_month", type text}, {"month_start", type date}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"avg_line_value", type number}, {"margin_pct", type number}, {"in_analysis_window", Int64.Type}})
				in
				    Typed
