table Monthly
	lineageTag: 5aa1b70c-4ae3-46f8-ac06-551ebef725eb

	column year_month
		dataType: string
		lineageTag: 2ea45570-3fb2-48f7-8a77-e0f9d5f9bfd8
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: 1ccc24f5-c7ff-4622-b988-f65506c18f84
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column year_number
		dataType: int64
		lineageTag: 1bd9a8b3-88cc-45f0-9f99-3116dfbece61
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 6af2d8e1-1aed-4e26-a873-ca819b48fbe1
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: 266a3d0f-b925-400e-ab51-ea1ba3901021
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 6454a07d-cd42-4c71-bb7b-70fc6e9ff7f0
		summarizeBy: none
		sourceColumn: month_name

	column transaction_lines
		dataType: int64
		lineageTag: 35d86f2c-3c01-49f5-b332-75c7d386a3e0
		summarizeBy: sum
		sourceColumn: transaction_lines

	column units_sold
		dataType: int64
		lineageTag: 8c90752f-7224-4de5-8057-f91b44cb89c3
		summarizeBy: sum
		sourceColumn: units_sold

	column revenue
		dataType: double
		lineageTag: 311e0ef9-77ab-48f4-ac9c-edd4aabf71a1
		summarizeBy: sum
		sourceColumn: revenue

	column profit
		dataType: double
		lineageTag: 7ed18e6c-155c-4a5e-a4e2-5ed9b0eec719
		summarizeBy: sum
		sourceColumn: profit

	column avg_line_value
		dataType: double
		lineageTag: aaf9f0a3-ca1b-4a0d-a23b-a09eac61d980
		summarizeBy: sum
		sourceColumn: avg_line_value

	column margin_pct
		dataType: double
		lineageTag: 242f94e7-4ab3-4de1-8ba8-ceee07a0598e
		summarizeBy: sum
		sourceColumn: margin_pct

	column in_analysis_window
		dataType: int64
		lineageTag: 2ad71041-edc6-485a-a814-8c85ab0f6a4b
		summarizeBy: sum
		sourceColumn: in_analysis_window

	partition Monthly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "monthly.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"year_month", type text}, {"month_start", type date}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"transaction_lines", Int64.Type}, {"units_sold", Int64.Type}, {"revenue", type number}, {"profit", type number}, {"avg_line_value", type number}, {"margin_pct", type number}, {"in_analysis_window", Int64.Type}})
				in
				    Typed
