table Sales
	lineageTag: 3593597c-ffe3-4475-989a-1061c46b2b86

	column sale_id
		dataType: int64
		lineageTag: 270edbc3-3469-436c-b2d8-6d66e9b1e202
		summarizeBy: sum
		sourceColumn: sale_id

	column order_ref
		dataType: string
		lineageTag: d9213ba2-8099-47a1-b1ce-9cb6da3382a2
		summarizeBy: none
		sourceColumn: order_ref

	column order_date
		dataType: dateTime
		lineageTag: df42ec25-ebec-492a-a09e-3222e3dc9a8b
		summarizeBy: none
		sourceColumn: order_date
		formatString: yyyy-mm-dd

	column customer_id
		dataType: int64
		lineageTag: 5b83a026-48d4-438f-bef8-4cb96d5c6555
		summarizeBy: sum
		sourceColumn: customer_id

	column year_number
		dataType: int64
		lineageTag: 603d7c76-3cb5-476c-bf5e-53ababadd2e7
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 406c5cd5-5d09-4282-8007-dbfe141c1924
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: f5e24860-7211-48ee-b483-5e4da4c060b5
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: c55801f6-2a12-41f3-8971-7d0443a7e8f6
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		lineageTag: 02b77fc7-32b6-463b-9df6-4ea51d29ca70
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: e8306a8b-3682-438d-bf39-24110e37ea94
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column is_complete_month
		dataType: int64
		lineageTag: 2ba958d6-f707-4ce2-8e04-b9e86414a9fd
		summarizeBy: sum
		sourceColumn: is_complete_month

	column is_complete_year
		dataType: int64
		lineageTag: 27be643b-f906-418f-a56f-4bbe5c59f06a
		summarizeBy: sum
		sourceColumn: is_complete_year

	column customer_name
		dataType: string
		lineageTag: 15e0140b-678a-4e7e-a9d7-7934a0d5279b
		summarizeBy: none
		sourceColumn: customer_name

	column city_name
		dataType: string
		lineageTag: 5ac05f12-381f-4689-9794-37adb256ec6f
		summarizeBy: none
		sourceColumn: city_name

	column state_name
		dataType: string
		lineageTag: d5dd9dab-5e52-4c33-9b0c-029a552709a3
		summarizeBy: none
		sourceColumn: state_name

	column category_name
		dataType: string
		lineageTag: 3e4eef22-6bd4-4966-804b-c1f51a265f50
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: ac041cce-dc7d-4dc9-971d-dee50cf06ff9
		summarizeBy: none
		sourceColumn: sub_category_name

	column payment_mode_name
		dataType: string
		lineageTag: 7f5be422-01a7-4467-9798-ded5ab3404cf
		summarizeBy: none
		sourceColumn: payment_mode_name

	column quantity
		dataType: int64
		lineageTag: a6a676af-0672-4abb-b8a5-ee1575b5e69c
		summarizeBy: sum
		sourceColumn: quantity

	column amount
		dataType: double
		lineageTag: 264f60e5-9562-432c-9abf-adc99273450f
		summarizeBy: sum
		sourceColumn: amount

	column profit
		dataType: double
		lineageTag: c4d433b1-3a5c-428f-93a4-4f75a1f0e584
		summarizeBy: sum
		sourceColumn: profit

	measure 'Revenue' = SUM ( Sales[amount] )
		formatString: #,0
		lineageTag: 0f698cac-cca0-4dfd-9dc5-c0726ab0d415

	measure 'Profit' = SUM ( Sales[profit] )
		formatString: #,0
		lineageTag: f3e33fc0-252c-44d7-91d2-2cb2925c42ba

	measure 'Orders' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: 91418a0b-3694-4028-bddd-563866b65f59

	measure 'Units' = SUM ( Sales[quantity] )
		formatString: #,0
		lineageTag: c9cecb73-b1dd-4c0c-9478-d6cafbd2bea7

	measure 'Customers' = DISTINCTCOUNT ( Sales[customer_id] )
		formatString: #,0
		lineageTag: ecbafe74-9fad-4a8c-91c4-4d392e9645dd

	measure 'Margin %' = DIVIDE ( [Profit], [Revenue] ) * 100
		formatString: #,0.00
		lineageTag: 54eda004-84b6-482c-9831-62246f2fa753

	measure 'Avg Line Value' = DIVIDE ( [Revenue], [Orders] )
		formatString: #,0.00
		lineageTag: 2de01105-978d-4394-b810-151a6b1f0071

	measure 'Months Covered' = DISTINCTCOUNT ( Sales[year_month] )
		formatString: #,0
		lineageTag: 42fe22be-efe4-4f9e-9d5b-7c13c616a067

	measure 'Revenue per Month' = DIVIDE ( [Revenue], [Months Covered] )
		formatString: #,0.00
		lineageTag: 0ad28d8b-be67-4ac5-afea-edf77f26d584

	measure 'Orders per Month' = DIVIDE ( [Orders], [Months Covered] )
		formatString: #,0.0
		lineageTag: f9aaa8c5-f744-431d-a8c3-5c01a059573d

	measure 'Peak Revenue per Month' = CALCULATE ( [Revenue per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.00
		lineageTag: 408bfd82-b346-4bcd-aa45-89f08bba353a

	measure 'Peak Orders per Month' = CALCULATE ( [Orders per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.0
		lineageTag: e6d1b227-42f5-4116-a838-56ac0b186189

	measure 'Gap to Peak %' = DIVIDE ( [Revenue per Month] - [Peak Revenue per Month], [Peak Revenue per Month] ) * 100
		formatString: #,0.0
		lineageTag: 9802e8ee-abc0-42ad-943b-acbfee8e3601

	measure 'Order Gap' = [Peak Orders per Month] - [Orders per Month]
		formatString: #,0.0
		lineageTag: 431609e7-f009-4a4f-b20e-f64ba4831196

	measure 'Gap Value per Year' = [Order Gap] * 5224.25 * 12
		formatString: #,0
		lineageTag: c7ef4fa0-6c5b-4eff-899f-ec2bd9f6c13e

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "sales_detail.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sale_id", Int64.Type}, {"order_ref", type text}, {"order_date", type date}, {"customer_id", Int64.Type}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"month_start", type date}, {"is_complete_month", Int64.Type}, {"is_complete_year", Int64.Type}, {"customer_name", type text}, {"city_name", type text}, {"state_name", type text}, {"category_name", type text}, {"sub_category_name", type text}, {"payment_mode_name", type text}, {"quantity", Int64.Type}, {"amount", type number}, {"profit", type number}})
				in
				    Typed
