table Sales
	lineageTag: 72ed724e-039a-431b-877c-37ccd47454b0

	column sale_id
		dataType: int64
		lineageTag: 7373628a-36da-4e2d-aa44-ffcdaa9c6369
		summarizeBy: sum
		sourceColumn: sale_id

	column order_ref
		dataType: string
		lineageTag: da63364d-39a6-4168-ba21-fb1e7711a0de
		summarizeBy: none
		sourceColumn: order_ref

	column order_date
		dataType: dateTime
		lineageTag: 652c7cde-8643-4d24-acd5-b29e4d781a66
		summarizeBy: none
		sourceColumn: order_date
		formatString: yyyy-mm-dd

	column customer_id
		dataType: int64
		lineageTag: 555a7edf-a07e-456c-8558-fda2a27c13d1
		summarizeBy: sum
		sourceColumn: customer_id

	column year_number
		dataType: int64
		lineageTag: 62711a1c-d231-462d-908e-458e9e09e2a7
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 36527663-7163-4ae1-b174-4563508b03dc
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: 28f04c93-3c9b-4f43-ab9d-79982bd31caf
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 3f638f36-5d69-4857-af0e-227321e963cc
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		lineageTag: 8dec110d-cf14-4720-bc65-06b514d74c8d
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: ebd18eba-7c12-40ce-9f24-a8f1d2fed94a
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column is_complete_month
		dataType: int64
		lineageTag: cad783b2-a10a-4074-88ef-b5705097dc49
		summarizeBy: sum
		sourceColumn: is_complete_month

	column is_complete_year
		dataType: int64
		lineageTag: 8bc314cc-0a65-4c0c-b8cc-25cf3f8a647d
		summarizeBy: sum
		sourceColumn: is_complete_year

	column customer_name
		dataType: string
		lineageTag: 6948397f-a444-4838-969e-2f16af719937
		summarizeBy: none
		sourceColumn: customer_name

	column city_name
		dataType: string
		lineageTag: 85f2ffcf-91da-4a58-95c0-df75309c1378
		summarizeBy: none
		sourceColumn: city_name

	column state_name
		dataType: string
		lineageTag: 338538e8-d19c-4ddb-9c04-282edd5a3387
		summarizeBy: none
		sourceColumn: state_name

	column category_name
		dataType: string
		lineageTag: ecb0c20a-983d-449f-8fa6-721c0b3b4810
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: ca5f534e-4da3-4026-a45b-c88790325491
		summarizeBy: none
		sourceColumn: sub_category_name

	column payment_mode_name
		dataType: string
		lineageTag: d7659d14-43d4-48c4-9892-4a5c12efd5ae
		summarizeBy: none
		sourceColumn: payment_mode_name

	column quantity
		dataType: int64
		lineageTag: 2078c011-17b9-4929-8914-6e6a16083449
		summarizeBy: sum
		sourceColumn: quantity

	column amount
		dataType: double
		lineageTag: 78596442-3ed7-43e2-ac09-3630120ef3ea
		summarizeBy: sum
		sourceColumn: amount

	column profit
		dataType: double
		lineageTag: fca757d4-b5cc-412d-be17-f10fc8a2c336
		summarizeBy: sum
		sourceColumn: profit

	measure 'Revenue' = SUM ( Sales[amount] )
		formatString: #,0
		lineageTag: 32771916-67e7-4448-bf30-39f4ef8fb8a1

	measure 'Total Profit' = SUM ( Sales[profit] )
		formatString: #,0
		lineageTag: 1a337e5e-1189-4db7-9cac-983ee5ed1fc5

	measure 'Orders' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: ed7b9729-20f5-45d8-a546-071b2fef01d5

	measure 'Units' = SUM ( Sales[quantity] )
		formatString: #,0
		lineageTag: fe208ef7-1a50-4abe-abb4-67724133b461

	measure 'Customers' = DISTINCTCOUNT ( Sales[customer_id] )
		formatString: #,0
		lineageTag: 0d7231be-0088-48eb-8bb4-58b22917f53d

	measure 'Margin %' = DIVIDE ( [Total Profit], [Revenue] ) * 100
		formatString: #,0.00
		lineageTag: 5460f168-6477-41ac-9c5a-5f683833fb00

	measure 'Avg Line Value' = DIVIDE ( [Revenue], [Orders] )
		formatString: #,0.00
		lineageTag: 2e0ab8f5-ba5d-4f9c-8dd7-1f2acb081e5b

	measure 'Months Covered' = DISTINCTCOUNT ( Sales[year_month] )
		formatString: #,0
		lineageTag: e9a067fe-7183-4f84-98bf-d332135f0ec3

	measure 'Revenue per Month' = DIVIDE ( [Revenue], [Months Covered] )
		formatString: #,0.00
		lineageTag: 01ab6ac6-e52d-4bc2-a1cf-32b701d16c9f

	measure 'Orders per Month' = DIVIDE ( [Orders], [Months Covered] )
		formatString: #,0.0
		lineageTag: 9256ea58-5951-4713-a7f3-bc550278a4e6

	measure 'Peak Revenue per Month' = CALCULATE ( [Revenue per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.00
		lineageTag: 17769e1b-7098-49e9-b68a-4bd5cdebc5e9

	measure 'Peak Orders per Month' = CALCULATE ( [Orders per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.0
		lineageTag: 60f0e8c0-6b42-4961-a3da-d06c36691427

	measure 'Gap to Peak %' = DIVIDE ( [Revenue per Month] - [Peak Revenue per Month], [Peak Revenue per Month] ) * 100
		formatString: #,0.0
		lineageTag: 959deff0-4534-48ed-a578-f0d8ddd391c9

	measure 'Order Gap' = [Peak Orders per Month] - [Orders per Month]
		formatString: #,0.0
		lineageTag: 66a56c08-e5c7-4f2d-b539-e0bd331f251d

	measure 'Gap Value per Year' = [Order Gap] * 5224.25 * 12
		formatString: #,0
		lineageTag: 632ab94f-4c05-46b3-8097-b85541aeffd0

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "sales_detail.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sale_id", Int64.Type}, {"order_ref", type text}, {"order_date", type date}, {"customer_id", Int64.Type}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"month_start", type date}, {"is_complete_month", Int64.Type}, {"is_complete_year", Int64.Type}, {"customer_name", type text}, {"city_name", type text}, {"state_name", type text}, {"category_name", type text}, {"sub_category_name", type text}, {"payment_mode_name", type text}, {"quantity", Int64.Type}, {"amount", type number}, {"profit", type number}})
				in
				    Typed
