table Sales
	lineageTag: e09e707a-e46a-48ac-b101-665042f39ea6

	column sale_id
		dataType: int64
		lineageTag: 3896f511-250a-4a58-aafd-0b5d241e9875
		summarizeBy: sum
		sourceColumn: sale_id

	column order_ref
		dataType: string
		lineageTag: 12f6585c-3cea-4a29-af0b-eaf93e855574
		summarizeBy: none
		sourceColumn: order_ref

	column order_date
		dataType: dateTime
		lineageTag: 299002d5-2cb3-47f1-9b90-2a133a2e5ecd
		summarizeBy: none
		sourceColumn: order_date
		formatString: yyyy-mm-dd

	column customer_id
		dataType: int64
		lineageTag: 02db91fe-9867-43c4-b1e0-657ad8419ffe
		summarizeBy: sum
		sourceColumn: customer_id

	column year_number
		dataType: int64
		lineageTag: 7f51bf79-335a-4b47-86d9-253bf89ce6cb
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: d6edd7f8-3042-4974-9157-74934a584700
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: 26518f68-c930-48b0-9407-bd29f25e96af
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: e4d778e8-ff82-4f8d-b325-4b67f9f9641d
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		lineageTag: dd5cc654-01b1-4aab-b099-358e31c642c1
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: 09091114-7920-4780-9e60-46d4eb56156f
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column is_complete_month
		dataType: int64
		lineageTag: f590adcc-1b8a-4718-9d20-1651849078ef
		summarizeBy: sum
		sourceColumn: is_complete_month

	column is_complete_year
		dataType: int64
		lineageTag: 46e4cbdf-fe0f-4f15-a0f0-c8d7dcf5ed95
		summarizeBy: sum
		sourceColumn: is_complete_year

	column customer_name
		dataType: string
		lineageTag: 80829e96-5a7f-419d-b57c-c1c3c146ddc2
		summarizeBy: none
		sourceColumn: customer_name

	column city_name
		dataType: string
		lineageTag: 955e0480-d845-42a4-8752-c98c50c99a95
		summarizeBy: none
		sourceColumn: city_name

	column state_name
		dataType: string
		lineageTag: e66df39b-58fd-4829-bfe1-59ac85f691b0
		summarizeBy: none
		sourceColumn: state_name

	column category_name
		dataType: string
		lineageTag: 7b57b09d-1879-4614-9ade-70351a082554
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: 7e611f01-ee36-42f7-ac25-ef81251657e1
		summarizeBy: none
		sourceColumn: sub_category_name

	column payment_mode_name
		dataType: string
		lineageTag: d2562ebf-1b86-4dda-b655-4e8e7cc6171a
		summarizeBy: none
		sourceColumn: payment_mode_name

	column quantity
		dataType: int64
		lineageTag: 3dc3541a-2fa6-4bbd-a17b-1a7860061bf7
		summarizeBy: sum
		sourceColumn: quantity

	column amount
		dataType: double
		lineageTag: b8fbe66e-ad1d-476e-9bf8-80eaaab80f37
		summarizeBy: sum
		sourceColumn: amount

	column profit
		dataType: double
		lineageTag: af06d661-829c-4383-8155-5bc29eac7329
		summarizeBy: sum
		sourceColumn: profit

	measure 'Revenue' = SUM ( Sales[amount] )
		formatString: #,0
		lineageTag: ba7de02c-2eb8-4a76-97fc-d1794746dfdb

	measure 'Total Profit' = SUM ( Sales[profit] )
		formatString: #,0
		lineageTag: eb306314-747b-42de-9760-29ac4c997908

	measure 'Orders' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: 8b292099-b414-4187-84ab-764213b15c0a

	measure 'Units' = SUM ( Sales[quantity] )
		formatString: #,0
		lineageTag: 5bc5277c-f8d4-47af-bb19-54bc7a3067c8

	measure 'Customers' = DISTINCTCOUNT ( Sales[customer_id] )
		formatString: #,0
		lineageTag: fe75247a-6c4d-4bac-b077-991c19f8d208

	measure 'Margin %' = DIVIDE ( [Total Profit], [Revenue] ) * 100
		formatString: #,0.00
		lineageTag: 093878a8-ad37-4db8-b20c-5aa4929cbee1

	measure 'Avg Line Value' = DIVIDE ( [Revenue], [Orders] )
		formatString: #,0.00
		lineageTag: 78e9d0df-1037-4eae-b9a1-e23993af4590

	measure 'Months Covered' = DISTINCTCOUNT ( Sales[year_month] )
		formatString: #,0
		lineageTag: 2b09cd30-0327-436f-b945-7436385ee0be

	measure 'Revenue per Month' = DIVIDE ( [Revenue], [Months Covered] )
		formatString: #,0.00
		lineageTag: 0ee4a9eb-4726-4b64-a7bb-651fe3fea5f3

	measure 'Orders per Month' = DIVIDE ( [Orders], [Months Covered] )
		formatString: #,0.0
		lineageTag: e266306a-34c5-46e3-8a55-59a1bf2c3e07

	measure 'Peak Revenue per Month' = CALCULATE ( [Revenue per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.00
		lineageTag: 6a30ce81-bb06-418b-80d0-fa1aaee2e8fd

	measure 'Peak Orders per Month' = CALCULATE ( [Orders per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.0
		lineageTag: 48f4824c-e542-4b8e-8add-71d3e6f93cc0

	measure 'Gap to Peak %' = DIVIDE ( [Revenue per Month] - [Peak Revenue per Month], [Peak Revenue per Month] ) * 100
		formatString: #,0.0
		lineageTag: ab854430-c79b-4c19-990c-3a8570834b76

	measure 'Order Gap' = [Peak Orders per Month] - [Orders per Month]
		formatString: #,0.0
		lineageTag: 0708e8be-0260-416f-b82d-54e3ce9de162

	measure 'Gap Value per Year' = [Order Gap] * 5224.25 * 12
		formatString: #,0
		lineageTag: 2ffe5f5e-4465-4f1e-8fbe-ce43c211000a

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "sales_detail.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sale_id", Int64.Type}, {"order_ref", type text}, {"order_date", type date}, {"customer_id", Int64.Type}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"month_start", type date}, {"is_complete_month", Int64.Type}, {"is_complete_year", Int64.Type}, {"customer_name", type text}, {"city_name", type text}, {"state_name", type text}, {"category_name", type text}, {"sub_category_name", type text}, {"payment_mode_name", type text}, {"quantity", Int64.Type}, {"amount", type number}, {"profit", type number}})
				in
				    Typed
