table Sales
	lineageTag: f7bbdaf8-4c3d-4360-8d05-9024875cd2fc

	column sale_id
		dataType: int64
		lineageTag: 20ef09d6-f1de-42f3-877a-f96f8bd06eef
		summarizeBy: sum
		sourceColumn: sale_id

	column order_ref
		dataType: string
		lineageTag: 0a0b7e4b-9305-4d68-bae8-397971c92965
		summarizeBy: none
		sourceColumn: order_ref

	column order_date
		dataType: dateTime
		lineageTag: aae7e3e6-3c16-47d8-a2c2-019b9c5ac542
		summarizeBy: none
		sourceColumn: order_date
		formatString: yyyy-mm-dd

	column customer_id
		dataType: int64
		lineageTag: b3af4ee0-f9f4-4e99-bb1e-76cccf1617a1
		summarizeBy: sum
		sourceColumn: customer_id

	column year_number
		dataType: int64
		lineageTag: d396dfd6-26e5-481f-94b8-68d0c17e69ab
		summarizeBy: sum
		sourceColumn: year_number

	column quarter_number
		dataType: int64
		lineageTag: 74af88ba-dede-438f-adff-17bdc2695d7c
		summarizeBy: sum
		sourceColumn: quarter_number

	column month_number
		dataType: int64
		lineageTag: 1acb7f1f-4908-42e8-aa81-e71bda636ec7
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 253703c3-552a-4e6e-81d4-341692b84961
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		lineageTag: ce29b907-890a-44ff-b356-659e537e9861
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		lineageTag: 6a355f47-4c9a-48b1-8ba5-3fac67e7e118
		summarizeBy: none
		sourceColumn: month_start
		formatString: yyyy-mm-dd

	column is_complete_month
		dataType: int64
		lineageTag: d559be0d-f22e-4eae-ad4f-4e8b175c43a7
		summarizeBy: sum
		sourceColumn: is_complete_month

	column is_complete_year
		dataType: int64
		lineageTag: 12194595-b3b9-4741-845e-8b8ad59f828a
		summarizeBy: sum
		sourceColumn: is_complete_year

	column customer_name
		dataType: string
		lineageTag: 4c1b2ce1-97ee-40ae-9913-20efff2bc06d
		summarizeBy: none
		sourceColumn: customer_name

	column city_name
		dataType: string
		lineageTag: 269067b8-5941-4307-a98d-ff67dfe51849
		summarizeBy: none
		sourceColumn: city_name

	column state_name
		dataType: string
		lineageTag: 62fc204a-57c7-4be1-acc0-064c2d1ea02a
		summarizeBy: none
		sourceColumn: state_name

	column category_name
		dataType: string
		lineageTag: 5ff3678b-406f-44b3-b9a7-e2d1da6258c1
		summarizeBy: none
		sourceColumn: category_name

	column sub_category_name
		dataType: string
		lineageTag: 02cc0e00-72d3-4cca-b96a-9149d95289d3
		summarizeBy: none
		sourceColumn: sub_category_name

	column payment_mode_name
		dataType: string
		lineageTag: 6283f912-84e7-4db2-b6a6-c5237e43d3e6
		summarizeBy: none
		sourceColumn: payment_mode_name

	column quantity
		dataType: int64
		lineageTag: 51c7c25d-dd00-4144-9ada-677cd505e436
		summarizeBy: sum
		sourceColumn: quantity

	column amount
		dataType: double
		lineageTag: 3bec8b7e-a95d-49a4-b55c-b3296dab5b58
		summarizeBy: sum
		sourceColumn: amount

	column profit
		dataType: double
		lineageTag: 2f9be5cc-a8d3-4e62-8d5a-92745f9d84df
		summarizeBy: sum
		sourceColumn: profit

	measure 'Revenue' = SUM ( Sales[amount] )
		formatString: #,0
		lineageTag: deb384f2-0100-4369-a646-5abc3b18db43

	measure 'Total Profit' = SUM ( Sales[profit] )
		formatString: #,0
		lineageTag: fb964a30-6931-4b6e-b468-67b9ffbef027

	measure 'Orders' = COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: eaeafcc8-955c-4627-a514-92c5870b7f2f

	measure 'Units' = SUM ( Sales[quantity] )
		formatString: #,0
		lineageTag: 0257bb6c-d0a9-41b4-a4c3-eebe62c6a559

	measure 'Customers' = DISTINCTCOUNT ( Sales[customer_id] )
		formatString: #,0
		lineageTag: daaff7f3-ca92-4ea8-81ab-f375c02ca8fe

	measure 'Margin %' = DIVIDE ( [Total Profit], [Revenue] ) * 100
		formatString: #,0.00
		lineageTag: f65801d2-1685-4a29-9aca-83bb6b42567e

	measure 'Avg Line Value' = DIVIDE ( [Revenue], [Orders] )
		formatString: #,0.00
		lineageTag: 83cf2e28-f2ee-4292-9cad-7292613d9a70

	measure 'Months Covered' = DISTINCTCOUNT ( Sales[year_month] )
		formatString: #,0
		lineageTag: 5737b6e1-7d75-41df-9f94-f2dac97c5e09

	measure 'Revenue per Month' = DIVIDE ( [Revenue], [Months Covered] )
		formatString: #,0.00
		lineageTag: 7e89b6de-acde-49eb-8f6e-514b257081d8

	measure 'Orders per Month' = DIVIDE ( [Orders], [Months Covered] )
		formatString: #,0.0
		lineageTag: d9c605af-eadb-4d42-b9e9-f56ecf29fb89

	measure 'Peak Revenue per Month' = CALCULATE ( [Revenue per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.00
		lineageTag: da9482ee-3857-4f94-9e73-b2905f5a2521

	measure 'Peak Orders per Month' = CALCULATE ( [Orders per Month], ALL ( Sales ), Sales[year_number] = 2022 )
		formatString: #,0.0
		lineageTag: 1b972657-dc52-4af2-8704-ec9cfb9364f7

	measure 'Gap to Peak %' = DIVIDE ( [Revenue per Month] - [Peak Revenue per Month], [Peak Revenue per Month] ) * 100
		formatString: #,0.0
		lineageTag: cfc6dd7a-329e-4cf6-9c9a-d57243a39c90

	measure 'Order Gap' = [Peak Orders per Month] - [Orders per Month]
		formatString: #,0.0
		lineageTag: 41dc3a7f-a44a-4410-b454-11cd75920aec

	measure 'Gap Value per Year' = [Order Gap] * 5224.25 * 12
		formatString: #,0
		lineageTag: 39ed1cc3-d3d5-4d01-a06a-900070552ba8

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "sales_detail.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sale_id", Int64.Type}, {"order_ref", type text}, {"order_date", type date}, {"customer_id", Int64.Type}, {"year_number", Int64.Type}, {"quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"month_start", type date}, {"is_complete_month", Int64.Type}, {"is_complete_year", Int64.Type}, {"customer_name", type text}, {"city_name", type text}, {"state_name", type text}, {"category_name", type text}, {"sub_category_name", type text}, {"payment_mode_name", type text}, {"quantity", Int64.Type}, {"amount", type number}, {"profit", type number}})
				in
				    Typed
