table SubcategorySegments
	lineageTag: 77d26b79-efa9-4ae1-831b-b7134a5deef9

	column sub_category_name
		dataType: string
		lineageTag: 8252173b-0312-4a88-a070-f2ea75d471f8
		summarizeBy: none
		sourceColumn: sub_category_name

	column category_name
		dataType: string
		lineageTag: 3bc01216-4793-4614-afac-c2de2c8808c8
		summarizeBy: none
		sourceColumn: category_name

	column revenue_total
		dataType: double
		lineageTag: 6955cbdf-7bed-4393-87cf-902635513e2a
		summarizeBy: sum
		sourceColumn: revenue_total

	column revenue_2023
		dataType: double
		lineageTag: 91cc63d0-2240-4c28-ac37-28c6bd98a844
		summarizeBy: sum
		sourceColumn: revenue_2023

	column revenue_2024
		dataType: double
		lineageTag: 72ebaffc-2bf6-48ae-b8d7-1060f2ef7c2a
		summarizeBy: sum
		sourceColumn: revenue_2024

	column growth_pct
		dataType: double
		lineageTag: 223cd715-590b-47a6-b5f7-50fe29054fc4
		summarizeBy: sum
		sourceColumn: growth_pct

	column margin_pct
		dataType: double
		lineageTag: 8585fd4f-d2e4-4819-b085-14cf3a963106
		summarizeBy: sum
		sourceColumn: margin_pct

	column cluster
		dataType: int64
		lineageTag: 65f22f14-2f61-438b-9def-1e169070c516
		summarizeBy: sum
		sourceColumn: cluster

	column segment
		dataType: string
		lineageTag: 795701bc-1ebb-4232-b478-44bdaaeb558e
		summarizeBy: none
		sourceColumn: segment

	partition SubcategorySegments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "subcategory_segments.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sub_category_name", type text}, {"category_name", type text}, {"revenue_total", type number}, {"revenue_2023", type number}, {"revenue_2024", type number}, {"growth_pct", type number}, {"margin_pct", type number}, {"cluster", Int64.Type}, {"segment", type text}})
				in
				    Typed
