table SubcategorySegments
	lineageTag: 783c596a-d4ee-4441-964c-96bbfdc2ba7f

	column sub_category_name
		dataType: string
		lineageTag: 34869ba8-de52-4f31-a91b-0c745a745c42
		summarizeBy: none
		sourceColumn: sub_category_name

	column category_name
		dataType: string
		lineageTag: 5058a744-1f07-4773-bc85-ac0ba1ba6706
		summarizeBy: none
		sourceColumn: category_name

	column revenue_total
		dataType: double
		lineageTag: aa98b7a3-a57e-4203-bf7e-3dbf2e0414ce
		summarizeBy: sum
		sourceColumn: revenue_total

	column revenue_2023
		dataType: double
		lineageTag: 30da4c73-23e0-409a-8c6b-885cfa4a2296
		summarizeBy: sum
		sourceColumn: revenue_2023

	column revenue_2024
		dataType: double
		lineageTag: 297739dd-4d51-4835-98de-c64af0005037
		summarizeBy: sum
		sourceColumn: revenue_2024

	column growth_pct
		dataType: double
		lineageTag: 19331f65-3d85-451b-8c53-915736f36993
		summarizeBy: sum
		sourceColumn: growth_pct

	column margin_pct
		dataType: double
		lineageTag: 27538e54-bb3f-43bb-a3f5-6d6b28864a16
		summarizeBy: sum
		sourceColumn: margin_pct

	column cluster
		dataType: int64
		lineageTag: a0278812-63bf-417d-a946-365562048231
		summarizeBy: sum
		sourceColumn: cluster

	column segment
		dataType: string
		lineageTag: 704279ec-1a2d-4bb8-9527-58ba59c4c0a7
		summarizeBy: none
		sourceColumn: segment

	partition SubcategorySegments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "subcategory_segments.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sub_category_name", type text}, {"category_name", type text}, {"revenue_total", type number}, {"revenue_2023", type number}, {"revenue_2024", type number}, {"growth_pct", type number}, {"margin_pct", type number}, {"cluster", Int64.Type}, {"segment", type text}})
				in
				    Typed
