table SubcategorySegments
	lineageTag: 92a13964-1846-489f-87e0-be939a48cb6b

	column sub_category_name
		dataType: string
		lineageTag: 5e259702-88a7-4e43-9b2e-f9f560020b47
		summarizeBy: none
		sourceColumn: sub_category_name

	column category_name
		dataType: string
		lineageTag: a72ba870-a0c8-45c9-9f7f-0b7949a13e1c
		summarizeBy: none
		sourceColumn: category_name

	column revenue_total
		dataType: double
		lineageTag: 96dd31de-089a-41bf-882e-f767dbf16c93
		summarizeBy: sum
		sourceColumn: revenue_total

	column revenue_2023
		dataType: double
		lineageTag: 950b263a-c689-411b-9e9d-c913dd7d45b0
		summarizeBy: sum
		sourceColumn: revenue_2023

	column revenue_2024
		dataType: double
		lineageTag: a72a588a-883f-4afd-8325-0f0206acdcf3
		summarizeBy: sum
		sourceColumn: revenue_2024

	column growth_pct
		dataType: double
		lineageTag: 9289447e-b583-4eeb-9279-a0fed703069a
		summarizeBy: sum
		sourceColumn: growth_pct

	column margin_pct
		dataType: double
		lineageTag: 7c5128ab-7a4e-4189-b388-f49acc30d206
		summarizeBy: sum
		sourceColumn: margin_pct

	column cluster
		dataType: int64
		lineageTag: 1aebe89f-c4f0-4c83-9f66-f6aa749f711d
		summarizeBy: sum
		sourceColumn: cluster

	column segment
		dataType: string
		lineageTag: 86f6f6a1-584e-41a4-8c30-59f565a8f975
		summarizeBy: none
		sourceColumn: segment

	partition SubcategorySegments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(FolderPath & "subcategory_segments.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"sub_category_name", type text}, {"category_name", type text}, {"revenue_total", type number}, {"revenue_2023", type number}, {"revenue_2024", type number}, {"growth_pct", type number}, {"margin_pct", type number}, {"cluster", Int64.Type}, {"segment", type text}})
				in
				    Typed
