"""
Runs every query in sql/04_queries.sql against the SQLite build of the
warehouse and writes the real result sets to reports/query_results.md.

The markdown tables are what goes into the "Result Screenshot" slots of
the Checkpoint 1 template - paste them, or screenshot them from the
rendered file / your MySQL Workbench run.

Run:  python3 scripts/run_queries.py
"""

import os
import re
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(ROOT, "data", "sales_trend.db")
QUERY_SQL = os.path.join(ROOT, "sql", "04_queries.sql")
OUT_MD = os.path.join(ROOT, "reports", "query_results.md")

GROUP_RE = re.compile(r"^-- \d\.\s+(.+)$")
QUERY_RE = re.compile(r"^-- (Q\d)\.\s+(.+)$")


def parse_queries(text):
    """Split the query file into (id, title, comment, sql) blocks."""
    blocks, group, qid, title, notes, body = [], None, None, None, [], []

    for line in text.splitlines():
        stripped = line.strip()

        if stripped.startswith("-- ") and stripped.isupper() is False:
            g = GROUP_RE.match(stripped)
            if g and qid is None:
                group = g.group(1)

        m = QUERY_RE.match(stripped)
        if m:
            qid, title, notes, body = m.group(1), m.group(2), [], []
            continue

        if qid is None:
            continue

        if stripped.startswith("--"):
            note = stripped.lstrip("-").strip()
            # Skip the ruled separator lines.
            if not note or set(note) <= {"-", "="}:
                continue
            # A title that wrapped onto the next comment line belongs to the
            # title, not the notes - it is still mid-sentence.
            if not notes and not body and not title.endswith("."):
                title = title + " " + note
            else:
                notes.append(note)
            continue

        body.append(line)
        if stripped.endswith(";"):
            # Keep the heading to one sentence; the rest reads as prose.
            head, sep, tail = title.partition(". ")
            blocks.append({
                "group": group,
                "id": qid,
                "title": head + "." if sep else head,
                "notes": ([tail] if sep else []) + notes,
                "sql": "\n".join(body).strip(),
            })
            qid = None
    return blocks


# Columns holding an ordinal rather than a quantity: printing 2024 as
# "2,024" would be wrong, so these are rendered bare.
PLAIN_COLUMNS = {"year", "month_no", "quarter", "sale_id", "year_month"}


def fmt(value, plain=False, pct=False):
    if value is None:
        return "—"
    if pct and isinstance(value, (int, float)):
        return f"{value:,.2f}"
    if isinstance(value, float) and value == int(value):
        value = int(value)
    if isinstance(value, int):
        return str(value) if plain else f"{value:,}"
    if isinstance(value, float):
        return f"{value:,.2f}"
    return str(value)


def as_table(cols, rows):
    if not rows:
        return "_(no rows returned)_"
    plain = [c.lower() in PLAIN_COLUMNS for c in cols]
    pct = [c.lower().endswith("_pct") for c in cols]
    out = ["| " + " | ".join(cols) + " |",
           "| " + " | ".join("---" for _ in cols) + " |"]
    for r in rows:
        out.append("| " + " | ".join(
            fmt(v, plain[i], pct[i]) for i, v in enumerate(r)) + " |")
    return "\n".join(out)


def main():
    con = sqlite3.connect(DB_PATH)
    blocks = parse_queries(open(QUERY_SQL, encoding="utf-8").read())

    md = [
        "# Task 1.4 — SQL Query Results",
        "",
        "Generated by `scripts/run_queries.py`. Every table below is the "
        "actual output of the matching query in `sql/04_queries.sql`, run "
        "against the populated warehouse — nothing here is typed by hand.",
        "",
        "> **Reading note.** The source data stops on 15 March 2025, so 2025 "
        "is a partial year. Trend queries restrict to `is_complete_year = 1` "
        "(2020–2024) so the cut-off is not mistaken for a drop in demand.",
        "",
    ]

    current_group = None
    for b in blocks:
        if b["group"] != current_group:
            current_group = b["group"]
            md += [f"## {current_group}", ""]
        md += [f"### {b['id']}. {b['title']}", ""]
        if b["notes"]:
            md += [" ".join(b["notes"]), ""]
        md += ["```sql", b["sql"], "```", ""]

        cur = con.execute(b["sql"])
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
        md += [f"**Result — {len(rows)} row(s):**", "", as_table(cols, rows), ""]
        print(f"{b['id']}: {len(rows)} rows")

    with open(OUT_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(md))
    con.close()
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
